# Generated by Django 5.0.6 on 2025-09-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CyclonePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sea_surface_temp', models.FloatField()),
                ('pressure', models.FloatField()),
                ('humidity', models.FloatField()),
                ('wind_shear', models.FloatField()),
                ('vorticity', models.FloatField()),
                ('latitude', models.FloatField()),
                ('ocean_depth', models.FloatField()),
                ('proximity', models.FloatField()),
                ('disturbance', models.IntegerField()),
                ('prediction', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
